name: update
on:
  schedule:
    - cron: '42 * * * *'
jobs:
  update-github-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: node index ${{ secrets.MY_TOKEN }}